version: '3'
services:
  wingetty:
    container_name: wingetty
    build:
      context: .
      dockerfile: Dockerfile
    image: wingetty
    ports:
      - 8080:8080
    volumes:
      - instance_volume:/app/instance # This is where the database will be stored
      - packages_volume:/app/app/packages # This is where the packages will be stored
    environment:
      - WINGETTY_DATABASE_URI="sqlite:///database.db" # You can use any database URI supported by SQLAlchemy, so you can use MySQL, PostgreSQL, etc.
      - WINGETTY_SECRET_KEY="secret" # Change this to a random string
      - WINGETTY_ENABLE_REGISTRATION=1 # Disable registration by setting this to 0, suggested after you have created your first user
      - WINGETTY_REPO_NAME = "WinGetty" # You can change this to whatever you want
volumes:
  instance_volume:
  packages_volume: